brutaldon/urls.py
from django.contrib import admin
from django.urls import path
from brutaldon import views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("about", views.about, name="about"),
    path("privacy", views.privacy, name="privacy"),
    path("home/next/<next>", views.home, name="home_next"),
    path("home/prev/<prev>", views.home, name="home_prev"),
    path("home", views.home, name="home"),
    path("login", views.login, name="login"),
    path("oldlogin", views.old_login, name="oldlogin"),
    path("logout", views.logout, name="logout"),
    path("oauth_callback", views.oauth_callback, name="oauth_callback"),
    path("error", views.error, name="error"),
    path("local", views.local, name="local"),
    path("local/next/<next>", views.local, name="local_next"),
    path("local/prev/<prev>", views.local, name="local_prev"),
    path("fed", views.fed, name="fed"),
    path("fed/next/<next>", views.fed, name="fed_next"),
    path("fed/prev/<prev>", views.fed, name="fed_prev"),
    path("note", views.note, name="note"),
    path("note/next<next>", views.note, name="note_next"),
    path("note/prev/<prev>", views.note, name="note_prev"),
    path("notes_count", views.notes_count, name="notes_count"),
    path("user_search", views.user_search, name="user_search"),
    path("settings", views.settings, name="settings"),
    path("thread/<id>", views.thread, name="thread"),
    path("tags/<tag>", views.tag, name="tag"),
    path("user/", views.home, name="user_bad"),
    path("user/<username>", views.user, name="user"),
    # next/prev are integers, but pleroma uses 128 bit integers
    # ...encoded in Base62.
    # aka a "flake_id"
    # from baseconv import base62, but we don't need to decode it
    # just pass it along back to pleroma but it is NOT an <int:>
    path("user/<username>/next/<next>", views.user, name="user_next"),
    path("user/<username>/prev/<prev>", views.user, name="user_prev"),
    path("toot/<mention>", views.toot, name="toot"),
    path("toot", views.toot, name="toot"),
    path("reply/<id>", views.reply, name="reply"),
    path("redraft/<id>", views.redraft, name="redraft"),
    path("fav/<id>", views.fav, name="fav"),
    path("boost/<id>", views.boost, name="boost"),
    path("delete/<id>", views.delete, name="delete"),
    path("follow/<id>", views.follow, name="follow"),
    path("block/<id>", views.block, name="block"),
    path("mute/<id>", views.mute, name="mute"),
    path("search", views.search, name="search"),
    path("search_results", views.search_results, name="search_results"),
    path("emoji", views.emoji_reference, name="emoji"),
    path("filters/list", views.list_filters, name="list_filters"),
    path("filters/create", views.create_filter, name="create_filter"),
    path("filters/delete/<id>", views.delete_filter, name="delete_filter"),
    path("filters/edit/<id>", views.edit_filter, name="edit_filter"),
    path("requests/", views.follow_requests, name="follow_requests"),
    path("requests/<id>", views.follow_requests, name="follow_requests"),
    path("accounts/", views.accounts, name="accounts"),
    path("accounts/<id>", views.accounts, name="accounts"),
    path("vote/<id>", views.vote, name="vote"),
    path("share/", views.share, name="share"),
    path("", views.home, name=""),
]

brutaldon/forms.py
from django import forms
from django.conf import settings
from django.utils.translation import gettext as _
from pytz import common_timezones
from .models import Theme, Preference


PRIVACY_CHOICES = (
    ("public", _("Public")),
    ("unlisted", _("Unlisted")),
    ("private", _("Private")),
    ("direct", _("Direct")),
)

timezones = [(tz, tz) for tz in common_timezones]


class LoginForm(forms.Form):
    instance = forms.CharField(label=_("Instance"), max_length=256)
    email = forms.EmailField(label=_("Email"))
    password = forms.CharField(widget=forms.PasswordInput())


class OAuthLoginForm(forms.Form):
    instance = forms.CharField(label=_("Instance"), max_length=256)


class PreferencesForm(forms.ModelForm):
    class Meta:
        model = Preference
        fields = Preference._fields


class PostForm(forms.Form):
    """def status_post(self, status, in_reply_to_id=None, media_ids=None,
                       sensitive=False, visibility=None, spoiler_text=None):"""

    status = forms.CharField(label="Toot", widget=forms.Textarea)
    visibility = forms.ChoiceField(
        label=_("Toot visibility"), choices=PRIVACY_CHOICES, required=False
    )
    spoiler_text = forms.CharField(label=_("CW or Subject"), required=False)
    media_file_1 = forms.FileField(label=_("Media 1"), required=False)
    media_text_1 = forms.CharField(label=_("Describe media 1."), required=False)
    media_file_2 = forms.FileField(label=_("Media 2"), required=False)
    media_text_2 = forms.CharField(label=_("Describe media 2."), required=False)
    media_file_3 = forms.FileField(label=_("Media 3"), required=False)
    media_text_3 = forms.CharField(label=_("Describe media 3."), required=False)
    media_file_4 = forms.FileField(label=_("Media 4"), required=False)
    media_text_4 = forms.CharField(label=_("Describe media 4."), required=False)
    media_sensitive = forms.BooleanField(label=_("Sensitive media?"), required=False)


class FilterForm(forms.Form):
    phrase = forms.CharField(label=_("Word or phrase to filter"))
    context_home = forms.BooleanField(
        label=_("In home timeline"), required=False, initial=True
    )
    context_public = forms.BooleanField(
        label=_("In public timelines"), required=False, initial=True
    )
    context_notes = forms.BooleanField(
        label=_("In notifications"), required=False, initial=True
    )
    context_thread = forms.BooleanField(
        label=_("In thread contexts"), required=False, initial=True
    )
    whole_word = forms.BooleanField(
        label=_("Whole words only"), required=False, initial=True
    )
    expires_in = forms.TypedChoiceField(
        label=_("Expires in"),
        choices=(
            ("", "Never"),
            ("1800", "30 minutes"),
            ("3600", "1 hour"),
            ("21600", "6 hours"),
            ("43200", "12 hours"),
            ("86400", "1 day"),
            ("604800", "1 week"),
        ),
        coerce=int,
        required=False,
    )

brutaldon/views.py
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.db import IntegrityError
from django.conf import settings as django_settings
from django.shortcuts import render, redirect
from django.urls import reverse
from django.views.decorators.cache import never_cache, cache_page
from django.core.files.uploadhandler import TemporaryFileUploadHandler
from django.utils.translation import gettext as _
from brutaldon.forms import (
    LoginForm,
    OAuthLoginForm,
    PreferencesForm,
    PostForm,
    FilterForm,
)
from brutaldon.models import Client, Account, Preference, Theme
from mastodon import (
    Mastodon,
    MastodonIllegalArgumentError,
    AttribAccessDict,
    MastodonError,
    MastodonAPIError,
    MastodonNotFoundError,
)
from urllib import parse
from pdb import set_trace
from itertools import groupby
from inscriptis import get_text
from time import sleep
from requests import Session
import re


class NotLoggedInException(Exception):
    pass


class LabeledList(list):
    """A subclass of list that can accept additional attributes"""

    def __new__(self, *args, **kwargs):
        return super(LabeledList, self).__new__(self, args, kwargs)

    def __init(self, *args, **kwargs):
        if len(args) == 1 and hasattr(args[0], "__iter__"):
            list.__init__(self, args[0])
        else:
            list.__init__(self, args)
        self.__dict__.update(kwargs)

    def __call(self, **kwargs):
        self.__dict__.update(kwargs)
        return self


global sessons_cache
sessions_cache = {}

VISIBILITIES = ["direct", "private", "unlisted", "public"]

###
### Utility functions
###


def get_session(domain):
    if domain in sessions_cache:
        return sessions_cache[domain]
    else:
        s = Session()
        sessions_cache[domain] = s
        return s


def get_usercontext(request, feature_set="mainline"):
    if is_logged_in(request):
        try:
            client = Client.objects.get(api_base_id=request.session["active_instance"])
            user = Account.objects.get(username=request.session["active_username"])
        except (
            Client.DoesNotExist,
            Client.MultipleObjectsReturned,
            Account.DoesNotExist,
            Account.MultipleObjectsReturned,
        ):
            raise NotLoggedInException()
        mastodon = Mastodon(
            client_id=client.client_id,
            client_secret=client.client_secret,
            access_token=user.access_token,
            api_base_url=client.api_base_id,
            session=get_session(client.api_base_id),
            ratelimit_method="throw",
            feature_set=feature_set,
            version_check_mode='none',
        )
        return user, mastodon
    else:
        return None, None


def is_logged_in(request):
    return request.session.has_key("active_user")


def _notes_count(account, mastodon):
    if not mastodon:
        return ""
    mastodon.version_check_mode = 'none'
    notes = mastodon.notifications(limit=40)
    if account.preferences.filter_notifications:
        notes = [
            note for note in notes if note.type == "mention" or note.type == "follow"
        ]
    for index, item in enumerate(notes):
        if account.note_seen is None:
            account.note_seen = "0"
            account.save()
        if str(item.id) <= str(account.note_seen):
            break
    else:
        index = "40+"
    return str(index)


def br_login_required(function=None, home_url=None, redirect_field_name=None):
    """Check that the user is logged in to a Mastodon instance.

    This decorator ensures that the view functions it is called on can be
    accessed only by logged in users. When an instanceless user accesses
    such a protected view, they are redirected to the address specified in
    the field named in `next_field` or, lacking such a value, the URL in
    `home_url`, or the `ANONYMOUS_HOME_URL` setting.
    """
    if home_url is None:
        home_url = django_settings.ANONYMOUS_HOME_URL

    def _dec(view_func):
        def _view(request, *args, **kwargs):
            def not_logged_in():
                url = None
                if redirect_field_name and redirect_field_name in request.REQUEST:
                    url = request.REQUEST[redirect_field_name]
                if not url:
                    url = home_url
                if not url:
                    url = "/"
                return HttpResponseRedirect(url)

            if not is_logged_in(request):
                return not_logged_in()
            else:
                try:
                    return view_func(request, *args, **kwargs)
                except MastodonAPIError:
                    # mastodon must have expired our session
                    return not_logged_in()

        _view.__name__ = view_func.__name__
        _view.__dict__ = view_func.__dict__
        _view.__doc__ = view_func.__doc__

        return _view

    if function is None:
        return _dec
    else:
        return _dec(function)


def user_search(request):
    check = request.POST.get("status", "").split()
    if len(check):
        check = check[-1]
        if len(check) > 1 and check.startswith("@"):
            check = check[1:]
            return user_search_inner(request, check)
        else:
            check = "&nbsp;"
    else:
        check = "&nbsp;"
    return HttpResponse(check)


def user_search_inner(request, query):
    account, mastodon = get_usercontext(request)
    mastodon.version_check_mode = 'none'
    results = mastodon.search(query)
    return render(
        request,
        "intercooler/users.html",
        {
            "users": "\n".join([user.acct for user in results.accounts]),
            "preferences": account.preferences,
        },
    )


def min_visibility(visibility1, visibility2):
    return VISIBILITIES[
        min(VISIBILITIES.index(visibility1), VISIBILITIES.index(visibility2))
    ]


def timeline(
    request,
    timeline="home",
    timeline_name="Home",
    max_id=None,
    min_id=None,
    filter_context="home",
):
    account, mastodon = get_usercontext(request)
    mastodon.version_check_mode = 'none'
    data = mastodon.timeline(timeline, limit=40, max_id=max_id, min_id=min_id)
    form = PostForm(
        initial={"visibility": request.session["active_user"].source.privacy}
    )
    try:
        prev = data[0]._pagination_prev
        if len(mastodon.timeline(min_id=prev["min_id"])) == 0:
            prev = None
        else:
            prev["min_id"] = data[0].id
    except (IndexError, AttributeError, KeyError):
        prev = None
    try:
        next = data[-1]._pagination_next
        next["max_id"] = data[-1].id
    except (IndexError, AttributeError, KeyError):
        next = None

    notifications = _notes_count(account, mastodon)
    filters = get_filters(mastodon, filter_context)

    # This filtering has to be done *after* getting next/prev links
    if account.preferences.filter_replies:
        data = [x for x in data if not x.in_reply_to_id]
    if account.preferences.filter_boosts:
        data = [x for x in data if not x.reblog]

    # Apply filters
    data = [x for x in data if not toot_matches_filters(x, filters)]

    return render(
        request,
        "main/%s_timeline.html" % timeline,
        {
            "toots": data,
            "form": form,
            "timeline": timeline,
            "timeline_name": timeline_name,
            "own_acct": request.session["active_user"],
            "preferences": account.preferences,
            "notifications": notifications,
            "prev": prev,
            "next": next,
        },
    )


def get_filters(mastodon, context=None):
    try:
        mastodon.version_check_mode = 'none'
        if context:
            return [ff for ff in mastodon.filters() if context in ff.context]
        else:
            return mastodon.filters()
    except:
        return []


def toot_matches_filters(toot, filters=[]):
    if not filters:
        return False

    def maybe_rewrite_filter(filter):
        if filter.whole_word:
            return f"\\b{filter.phrase}\\b"
        else:
            return filter.phrase

    phrases = [maybe_rewrite_filter(x) for x in filters]
    pattern = "|".join(phrases)
    try:
        if toot.get("type") in ["reblog", "favourite"]:
            return re.search(
                pattern, toot.status.spoiler_text + toot.status.content, re.I
            )
        return re.search(pattern, toot.spoiler_text + toot.content, re.I)
    except:
        return False


def switch_accounts(request, new_account):
    """Try to switch accounts to the specified account, if it is already in
    the user's session. Sets up new session variables. Returns boolean success
    code."""
    accounts_dict = request.session.get("accounts_dict")
    if not accounts_dict or not new_account in accounts_dict.keys():
        return False
    try:
        account = Account.objects.get(id=accounts_dict[new_account]["account_id"])
        if account.username != new_account:
            return False
    except Account.DoesNotExist:
        return False

    request.session["active_username"] = account.username
    request.session["active_instance"] = account.client.api_base_id
    account, mastodon = get_usercontext(request)
    request.session["active_user"] = mastodon.account_verify_credentials()
    accounts_dict[new_account]["user"] = request.session["active_user"]
    request.session["accounts_dict"] = accounts_dict
    return True


def forget_account(request, account_name):
    """Forget that you were logged into an account. If it's the last one, log out
    entirely. Sets up session variables. Returns a redirect to the correct
    view.
    """
    accounts_dict = request.session.get("accounts_dict")
    if not accounts_dict or not account_name in accounts_dict.keys():
        return redirect("accounts")
    del accounts_dict[account_name]

brutaldon/templates/main/boost.html
{% extends "base.html" %}

{% block title  %} Brutaldon ({{ own_acct.username }}) - confirm boost {% endblock %}

{% block content %}
{% if toot.reblogged %}
<h1 class="title">Unboost that toot?</h1>
{% else %}
<h1 class="title" >Boost that toot?</h1>
{% endif %}

{% include "main/toot_partial.html" with toot=toot %}
<form method="POST" action="{% url "boost" toot.id %}">
    {% csrf_token %}
    <div class="level is-mobile">
        <div class="level-left">
            <div class="level-item">
                <input class="button" type="submit" name="cancel" value="Cancel">
            </div>
        </div>
        <div class="level-right">
            <div class="level-item">
                {% if toot.reblogged %}
                <input class="button is-primary" type="submit" name="boost"
                       value="Unboost">
                {% else %}
                <input class="button is-primary" type="submit" name="boost"
                       value="Boost">
                {% endif %}
            </div>
        </div>
    </div>
</form>
{% endblock %}

brutaldon/templates/main/emoji.html
{% extends "base.html" %}

{% block title %}Brutaldon ({{ own_acct.username }}) - Custom emoji reference {% endblock %}

{% block content %}
    <section>
        <h1 class="title">Custom emoji reference</h1>
        <p class="subtitle">
            Copy shortcodes from the list below to use your instance's custom emoji.
        </p>
    </section>

    <hr>
    <section>
        <div class="columns is-9 is-variable is-centered is-multiline">
            {% for emojo in emojos  %}
                <div class="column is-one-fifth">
                    <p class="level emoji-box">
                        <img alt="" class="level-item emoji" src="{{ emojo.url }}">
                        <span class="level-item">:{{ emojo.shortcode }}:</span>
                    </p>
                </div>
            {% endfor %}
        </div>
    </section>
{% endblock %}

brutaldon/templates/main/fav.html
{% extends "base.html" %}

{% block title  %} Brutaldon ({{ own_acct.username }}) - confirm favorite {% endblock %}

{% block content %}
{% if toot.favourited %}
<h1 class="title">Unfav that toot?</h1>
{% else %}
<h1 class="title" >Fav that toot?</h1>
{% endif %}

{% include "main/toot_partial.html" with toot=toot %}
<form method="POST" action="{% url "fav" toot.id %}">
    {% csrf_token %}
    <div class="level is-mobile">
        <div class="level-left">
            <div class="level-item">
                <input class="button" type="submit" name="cancel" value="Cancel">
            </div>
        </div>
        <div class="level-right">
            <div class="level-item">
                {% if toot.favorited %}
                <input class="button is-primary" type="submit" name="fav"
                       value="Unfavorite">
                {% else %}
                <input class="button is-primary" type="submit" name="fav"
                       value="Favorite">
                {% endif %}
            </div>
        </div>
    </div>
</form>
{% endblock %}

brutaldon/templates/main/home_timeline.html
{% extends "main/timeline.html" %}

brutaldon/templates/main/mute.html
{% extends "base.html" %}
{% load taglinks %}
{% load sanitizer %}

{% block title %}Brutaldon - confirm (un)mute {% endblock %}

{% block content %}
    {% if relationship.muting %}
        <h1 class="title">Unmute this user?</h1>
    {% else %}
        <h1 class="title">Mute this user?</h1>
    {% endif %}

    <article class="media user-info">
        <figure class="media-left">
            <p class="image is-64x64">
                <a href="{% url "user" user.acct %}">
                    <img src="{{ user.avatar }}"
                         alt="">
                </a>
            </p>
        </figure>
        <div class="media-content">
            <div class="content">
                <p>
                    <strong>{{ user.display_name }}</strong>
                    <small>
                        <a href="{% url "user" user.acct %}">
                            @{{ user.acct }}
                        </a>
                    </small>
                </p>
                {{ user.note | relink_toot | strip_html | safe }}
                <p>
                </p>

            </div>
        </div>
    </article>

    <form method="POST" action="{% url 'mute' user.id %}">
        {% csrf_token %}
        <div class="level is-mobile">
            <div class="level-left">
                <div class="level-item">
                    <input class="button" type="submit" name="cancel" value="Cancel">
                </div>
            </div>
            <div class="level-right">
                <div class="level-item">
                    <input class="button is-primary" type="submit" name="mute"
                           value="Confirm">
                </div>
            </div>
        </div>
    </form>

{% endblock %}

brutaldon/templates/main/post_minimal_partial.html
{% load widget_tweaks %}
<form method="post" id="post-form" action="{% url "toot" %}" enctype="multipart/form-data">
    {% csrf_token %}

    <div>
        {{ form.non_field_errors }}
        <br>
    </div>

    <div class="field">
        <label class="label"> {{ form.spoiler_text.label }}</label>
        <div class="control">
            {% render_field form.spoiler_text class+="input mousetrap" placeholder="Optional" %}
        </div>
    </div>

    <div class="field" >
        <label class="label" >{{ form.status.label }}</label>
        <div class="control">
            <textarea name="status" cols="40" rows="3" class="textarea is-primary mousetrap"
                      required="" id="id_status"
                      ic-post-to="{% url "user_search" %}"
                      ic-trigger-on="keyup changed" ic-trigger-delay="500ms"
                      ic-target="#username_autocomplete">{% if form.status.value %}{{ form.status.value }}{% endif %}</textarea>
            <div id="username_autocomplete"></div>
        </div>
        <div id="status_count"></div>
    </div>

    <div class="field has-addons">
        <div class="control  level is-mobile">
            <a href="{% url "user" own_acct.acct %}" class="image avatar is-48x48 level-item">
                <img src="{{ own_acct.avatar_static }}" alt="[{{ own_acct.acct }}]">
            </a>
            <input type="submit" class="button is-primary level-item"
                   name="toot" value="Toot">
            <a href="{% url "emoji" %}" target="_blank"  rel="noopener noreferrer"
               class="level-item emoji-link" title="custom emoji reference">😊</a>
            <a href="{% url "toot" %}"
               ic-get-from="{% url "toot" %}"
               ic-target="#post-form"
               ic-select-from-response="#post-form"
               ic-include="#id_status,#id_spoiler_text"
               title="Complete toot form (media, visibility, etc"
               class="fa fa-edit">
                <span class="is-hidden">Complete toot form (media, visibility etc)</span>
            </a>
        </div>
    </div>
    {% if not preferences.theme.no_javascript %}
        <script type="application/javascript">
         Intercooler.ready(characterCountSetup);
        </script>
    {% endif %}
</form>

brutaldon/templates/main/post_partial.html
{% load widget_tweaks %}

{% if reply %}
    <form method="post" id="post-form" action="{% url "reply" toot.id %}" enctype="multipart/form-data">
{% elif redraft %}
        <form method="post" id="post-form" action="{% url "redraft" toot.id %}" enctype="multipart/form-data">
{% else %}
            <form id="post-form" method="post" action="{% url "toot" %}" enctype="multipart/form-data">
{% endif %}
{% csrf_token %}

<div>
    {{ form.non_field_errors }}
    <br>
</div>

<div class="field">
    <label class="label"> {{ form.spoiler_text.label }}</label>
    <div class="control">
        {% render_field form.spoiler_text class+="input mousetrap" placeholder="Optional" %}
    </div>
</div>

<div class="field" >
    <label class="label" >{{ form.status.label }}</label>
    <div class="control">
        <textarea name="status" cols="40" rows="3" class="textarea is-primary mousetrap"
                  required="" id="id_status"
                  ic-post-to="{% url "user_search" %}"
                  ic-trigger-on="keyup changed" ic-trigger-delay="500ms"
                  ic-target="#username_autocomplete">{% if form.status.value %}{{ form.status.value }}{% endif %}</textarea>
        <div id="username_autocomplete"></div>
    </div>
    <div id="status_count"></div>
</div>

<div class="field">
    <label class="label" > {{ form.visibility.label }}</label>
    <div class="control has-icons-left">
        <div class="select">
            {% render_field form.visibility class+="select"%}
            <span class="icon is-small is-left" >
                <i class="fa fa-address-card"></i>
            </span>
        </div>
    </div>
</div>

<div class="field has-addons">
    <div class="file">
        <label class="file-label">
            {% render_field form.media_file_1 class+="file-input" %}
            <span class="file-cta">
                <span class="file-icon">
                    <i class="fa fa-upload"></i>
                </span>
                <span class="file-label" id="media_filename_1">
                    {{ form.media_file_1.label }}
                </span>
            </span>
        </label>
    </div>
    <div class="control is-expanded">
        {% render_field form.media_text_1 class+="input mousetrap" placeholder="Describe attachment" %}
    </div>
</div>

<div class="field has-addons">
    <div class="file">
        <label class="file-label">
            {% render_field form.media_file_2 class+="file-input" %}
            <span class="file-cta">
                <span class="file-icon">
                    <i class="fa fa-upload"></i>
                </span>
                <span class="file-label" id="media_filename_2">
                    {{ form.media_file_2.label }}
                </span>
            </span>
        </label>
    </div>
    <div class="control is-expanded">
        {% render_field form.media_text_2 class+="input mousetrap" placeholder="Describe attachment" %}
    </div>
</div>

<div class="field has-addons">
    <div class="file">
        <label class="file-label">
            {% render_field form.media_file_3 class+="file-input" %}
            <span class="file-cta">
                <span class="file-icon">
                    <i class="fa fa-upload"></i>
                </span>
                <span class="file-label" id="media_filename_3">
                    {{ form.media_file_3.label }}
                </span>
            </span>
        </label>
    </div>
    <div class="control is-expanded">
        {% render_field form.media_text_3 class+="input mousetrap" placeholder="Describe attachment" %}
    </div>
</div>
<div class="field has-addons">
    <div class="file">
        <label class="file-label">
            {% render_field form.media_file_4 class+="file-input" %}
            <span class="file-cta">
                <span class="file-icon">
                    <i class="fa fa-upload"></i>
                </span>
                <span class="file-label" id="media_filename_4">
                    {{ form.media_file_4.label }}
                </span>
            </span>
        </label>
    </div>
    <div class="control is-expanded">
        {% render_field form.media_text_4 class+="input mousetrap" placeholder="Describe attachment" %}
    </div>
</div>


<div class="field has-addons">
    <div class="control level is-mobile">
        <a href="{% url "user" own_acct.acct %}" class="image avatar is-48x48 level-item" >
            <img src="{{ own_acct.avatar_static }}" alt="[{{ own_acct.acct }}]">
        </a>
        <input type="submit" class="button is-primary level-item"
               name="toot" value="Toot">
        <a href="{% url "emoji" %}" target="_blank"  rel="noopener noreferrer"
           class="level-item emoji-link" title="custom emoji reference">😊</a>
    </div>
</div>
{% if not preferences.no_javascript %}
    <script type="application/javascript">
     fileButtonUpdaters();
     Intercooler.ready(fileButtonUpdaters);
     Intercooler.ready(characterCountSetup);
    </script>
{% endif %}
            </form>

brutaldon/templates/main/redraft.html
{% extends "base.html" %}
{% load humanize %}
{% load static %}

{% block title %}
Brutaldon ({{ own_acct.username }}) - reply
{% endblock %}

{% block page_scripts %}
    <script src="{% static 'js/mousetrap.min.js' %}" type="application/javascript"></script>
{% endblock %}

{% block content %}
    <h1 class="title">Redraft</h1>
    {% include "main/toot_partial.html" with toot=toot active=True %}
    <hr class="is-hidden">
    <div class="notification">
        <p>
            Submitting this form will <em>post</em> this replacement toot, and
            <em class="error">delete</em> the original toot. The replacement toot will not
            have any favs, boosts, or replies that the original toot had.
            Currently, media attachments must be re-uploaded. Sorry, working on it.
        </p>
    </div>

    <div class="box">
        {% include "main/post_partial.html" %}
    </div>

{% endblock %}

{% block page_scripts_inline %}
    <script type="application/javascript">
     document.addEventListener('DOMContentLoaded', function () {
         Mousetrap.bind('ctrl+enter', function(e) {
             var form = document.querySelector('#post-form');
             form.submit();
             return true;
         });
     });
    </script>
{% endblock %}

brutaldon/templates/main/reply.html
{% extends "base.html" %}
{% load humanize %}
{% load static %}

{% block title %}
Brutaldon ({{ own_acct.username }}) - reply
{% endblock %}

{% block page_scripts %}
    <script src="{% static 'js/mousetrap.min.js' %}" type="application/javascript"></script>
{% endblock %}

{% block content %}
    <h1 class="title">Thread</h1>
    {% for ancestor in context.ancestors %}
        {% include "main/toot_partial.html" with toot=ancestor %}
        <hr class="is-hidden">
    {% endfor %}
    {% include "main/toot_partial.html" with toot=toot active=True %}
    <hr class="is-hidden">
    <div class="box">
        {% include "main/post_partial.html" %}
    </div>

{% endblock %}

{% block page_scripts_inline %}
    <script type="application/javascript">
     document.addEventListener('DOMContentLoaded', function () {
         Mousetrap.bind('ctrl+enter', function(e) {
             var form = document.querySelector('#post-form');
             form.submit();
             return true;
         });
     });
    </script>
{% endblock %}