brutaldon/urls.py
from django.contrib import admin
from django.urls import path
from brutaldon import views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("about", views.about, name="about"),
    path("privacy", views.privacy, name="privacy"),
    path("home/next/<next>", views.home, name="home_next"),
    path("home/prev/<prev>", views.home, name="home_prev"),
    path("home", views.home, name="home"),
    path("login", views.login, name="login"),
    path("oldlogin", views.old_login, name="oldlogin"),
    path("logout", views.logout, name="logout"),
    path("oauth_callback", views.oauth_callback, name="oauth_callback"),
    path("error", views.error, name="error"),
    path("local", views.local, name="local"),
    path("local/next/<next>", views.local, name="local_next"),
    path("local/prev/<prev>", views.local, name="local_prev"),
    path("fed", views.fed, name="fed"),
    path("fed/next/<next>", views.fed, name="fed_next"),
    path("fed/prev/<prev>", views.fed, name="fed_prev"),
    path("note", views.note, name="note"),
    path("note/next<next>", views.note, name="note_next"),
    path("note/prev/<prev>", views.note, name="note_prev"),
    path("notes_count", views.notes_count, name="notes_count"),
    path("user_search", views.user_search, name="user_search"),
    path("settings", views.settings, name="settings"),
    path("thread/<id>", views.thread, name="thread"),
    path("tags/<tag>", views.tag, name="tag"),
    path("user/", views.home, name="user_bad"),
    path("user/<username>", views.user, name="user"),
    # next/prev are integers, but pleroma uses 128 bit integers
    # ...encoded in Base62.
    # aka a "flake_id"
    # from baseconv import base62, but we don't need to decode it
    # just pass it along back to pleroma but it is NOT an <int:>
    path("user/<username>/next/<next>", views.user, name="user_next"),
    path("user/<username>/prev/<prev>", views.user, name="user_prev"),
    path("toot/<mention>", views.toot, name="toot"),
    path("toot", views.toot, name="toot"),
    path("reply/<id>", views.reply, name="reply"),
    path("redraft/<id>", views.redraft, name="redraft"),
    path("fav/<id>", views.fav, name="fav"),
    path("boost/<id>", views.boost, name="boost"),
    path("delete/<id>", views.delete, name="delete"),
    path("follow/<id>", views.follow, name="follow"),
    path("block/<id>", views.block, name="block"),
    path("mute/<id>", views.mute, name="mute"),
    path("search", views.search, name="search"),
    path("search_results", views.search_results, name="search_results"),
    path("emoji", views.emoji_reference, name="emoji"),
    path("filters/list", views.list_filters, name="list_filters"),
    path("filters/create", views.create_filter, name="create_filter"),
    path("filters/delete/<id>", views.delete_filter, name="delete_filter"),
    path("filters/edit/<id>", views.edit_filter, name="edit_filter"),
    path("requests/", views.follow_requests, name="follow_requests"),
    path("requests/<id>", views.follow_requests, name="follow_requests"),
    path("accounts/", views.accounts, name="accounts"),
    path("accounts/<id>", views.accounts, name="accounts"),
    path("vote/<id>", views.vote, name="vote"),
    path("share/", views.share, name="share"),
    path("", views.home, name=""),
]

brutaldon/models.py
from django.db import models
from django.conf import settings
from django.utils.translation import gettext as _
from pytz import common_timezones

timezones = [(tz, tz) for tz in common_timezones]


class Client(models.Model):
    name = models.CharField(default="brutaldon", max_length=80)
    api_base_id = models.URLField(default="https://mastodon.social")
    version = models.CharField(default="1.0", max_length=80)
    client_id = models.CharField(null=True, blank=True, max_length=2048)
    client_secret = models.CharField(null=True, blank=True, max_length=2048)

    def __str__(self):
        return self.name + ": " + self.api_base_id


class Theme(models.Model):
    name = models.CharField(max_length=80, unique=True)
    prefix = models.CharField(max_length=40, null=True, default="default")
    main_css = models.CharField(
        max_length=1024, blank=True, null=True, default="css/fullbrutalism.css"
    )
    tweaks_css = models.CharField(max_length=1024, blank=True, null=True)
    is_brutalist = models.BooleanField(default=False)

    def __str__(self):
        return self.name


from django.db.models.fields.related_descriptors import ForeignKeyDeferredAttribute


def set_fields(klass):
    fields = []
    for n in dir(klass):
        assert n != "_fields"
        v = getattr(klass, n)
        if not hasattr(v, "field"):
            continue
        if not isinstance(v.field, models.Field):
            continue
        if isinstance(v, ForeignKeyDeferredAttribute):
            continue
        fields.append(n)
    setattr(klass, "_fields", fields)
    return klass


@set_fields
class Preference(models.Model):
    theme = models.ForeignKey(Theme, models.CASCADE, null=False, default=1)
    filter_replies = models.BooleanField(default=False)
    filter_boosts = models.BooleanField(default=False)
    timezone = models.CharField(
        max_length=80, blank=True, null=True, choices=timezones, default="UTC"
    )
    preview_sensitive = models.BooleanField(
        default=False, help_text=_('Show preview for media marked as "sensitive"')
    )

    no_javascript = models.BooleanField(
        default=False,
        help_text=_(
            """Disable all JavaScript. Overrides all other JavaScript options."""
        ),
    )
    notifications = models.BooleanField(
        default=True, help_text=_("""Display live notifications in header.""")
    )
    click_to_load = models.BooleanField(
        default=False,
        help_text=_(
            """Click to load more toots in the same page, rather than using pagination."""
        ),
    )
    lightbox = models.BooleanField(
        default=False, help_text=_("""Use a JavaScript lightbox to display media.""")
    )
    poll_frequency = models.IntegerField(
        default=300,
        help_text=_(
            """Number of seconds to wait between checking notifications. Default: 300"""
        ),
    )
    filter_notifications = models.BooleanField(
        default=False,
        help_text=_("""Exclude boosts and favs from your notifications."""),
    )
    bundle_notifications = models.BooleanField(
        default=False,
        help_text=_(
            """Collapse together boosts or likes of the same toot in the notifications page."""
        ),
    )


class Account(models.Model):
    username = models.EmailField(unique=True)
    email = models.EmailField(null=True, blank=True)
    django_user = models.ForeignKey(settings.AUTH_USER_MODEL, models.CASCADE, null=True)
    access_token = models.CharField(null=True, blank=True, max_length=2048)
    client = models.ForeignKey(Client, models.SET_NULL, null=True)
    preferences = models.ForeignKey(Preference, models.SET_NULL, null=True)
    note_seen = models.CharField(null=True, blank=True, max_length=128)

brutaldon/views.py
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.db import IntegrityError
from django.conf import settings as django_settings
from django.shortcuts import render, redirect
from django.urls import reverse
from django.views.decorators.cache import never_cache, cache_page
from django.core.files.uploadhandler import TemporaryFileUploadHandler
from django.utils.translation import gettext as _
from brutaldon.forms import (
    LoginForm,
    OAuthLoginForm,
    PreferencesForm,
    PostForm,
    FilterForm,
)
from brutaldon.models import Client, Account, Preference, Theme
from mastodon import (
    Mastodon,
    MastodonIllegalArgumentError,
    AttribAccessDict,
    MastodonError,
    MastodonAPIError,
    MastodonNotFoundError,
)
from urllib import parse
from pdb import set_trace
from itertools import groupby
from inscriptis import get_text
from time import sleep
from requests import Session
import re


class NotLoggedInException(Exception):
    pass


class LabeledList(list):
    """A subclass of list that can accept additional attributes"""

    def __new__(self, *args, **kwargs):
        return super(LabeledList, self).__new__(self, args, kwargs)

    def __init(self, *args, **kwargs):
        if len(args) == 1 and hasattr(args[0], "__iter__"):
            list.__init__(self, args[0])
        else:
            list.__init__(self, args)
        self.__dict__.update(kwargs)

    def __call(self, **kwargs):
        self.__dict__.update(kwargs)
        return self


global sessons_cache
sessions_cache = {}

VISIBILITIES = ["direct", "private", "unlisted", "public"]

###
### Utility functions
###


def get_session(domain):
    if domain in sessions_cache:
        return sessions_cache[domain]
    else:
        s = Session()
        sessions_cache[domain] = s
        return s


def get_usercontext(request, feature_set="mainline"):
    if is_logged_in(request):
        try:
            client = Client.objects.get(api_base_id=request.session["active_instance"])
            user = Account.objects.get(username=request.session["active_username"])
        except (
            Client.DoesNotExist,
            Client.MultipleObjectsReturned,
            Account.DoesNotExist,
            Account.MultipleObjectsReturned,
        ):
            raise NotLoggedInException()
        mastodon = Mastodon(
            client_id=client.client_id,
            client_secret=client.client_secret,
            access_token=user.access_token,
            api_base_url=client.api_base_id,
            session=get_session(client.api_base_id),
            ratelimit_method="throw",
            feature_set=feature_set,
            version_check_mode='none',
        )
        return user, mastodon
    else:
        return None, None


def is_logged_in(request):
    return request.session.has_key("active_user")


def _notes_count(account, mastodon):
    if not mastodon:
        return ""
    mastodon.version_check_mode = 'none'
    notes = mastodon.notifications(limit=40)
    if account.preferences.filter_notifications:
        notes = [
            note for note in notes if note.type == "mention" or note.type == "follow"
        ]
    for index, item in enumerate(notes):
        if account.note_seen is None:
            account.note_seen = "0"
            account.save()
        if str(item.id) <= str(account.note_seen):
            break
    else:
        index = "40+"
    return str(index)


def br_login_required(function=None, home_url=None, redirect_field_name=None):
    """Check that the user is logged in to a Mastodon instance.

    This decorator ensures that the view functions it is called on can be
    accessed only by logged in users. When an instanceless user accesses
    such a protected view, they are redirected to the address specified in
    the field named in `next_field` or, lacking such a value, the URL in
    `home_url`, or the `ANONYMOUS_HOME_URL` setting.
    """
    if home_url is None:
        home_url = django_settings.ANONYMOUS_HOME_URL

    def _dec(view_func):
        def _view(request, *args, **kwargs):
            def not_logged_in():
                url = None
                if redirect_field_name and redirect_field_name in request.REQUEST:
                    url = request.REQUEST[redirect_field_name]
                if not url:
                    url = home_url
                if not url:
                    url = "/"
                return HttpResponseRedirect(url)

            if not is_logged_in(request):
                return not_logged_in()
            else:
                try:
                    return view_func(request, *args, **kwargs)
                except MastodonAPIError:
                    # mastodon must have expired our session
                    return not_logged_in()

        _view.__name__ = view_func.__name__
        _view.__dict__ = view_func.__dict__
        _view.__doc__ = view_func.__doc__

        return _view

    if function is None:
        return _dec
    else:
        return _dec(function)


def user_search(request):
    check = request.POST.get("status", "").split()
    if len(check):
        check = check[-1]
        if len(check) > 1 and check.startswith("@"):
            check = check[1:]
            return user_search_inner(request, check)
        else:
            check = "&nbsp;"
    else:
        check = "&nbsp;"
    return HttpResponse(check)


def user_search_inner(request, query):
    account, mastodon = get_usercontext(request)
    mastodon.version_check_mode = 'none'
    results = mastodon.search(query)
    return render(
        request,
        "intercooler/users.html",
        {
            "users": "\n".join([user.acct for user in results.accounts]),
            "preferences": account.preferences,
        },
    )


def min_visibility(visibility1, visibility2):
    return VISIBILITIES[
        min(VISIBILITIES.index(visibility1), VISIBILITIES.index(visibility2))
    ]


def timeline(
    request,
    timeline="home",
    timeline_name="Home",
    max_id=None,
    min_id=None,
    filter_context="home",
):
    account, mastodon = get_usercontext(request)
    mastodon.version_check_mode = 'none'
    data = mastodon.timeline(timeline, limit=40, max_id=max_id, min_id=min_id)
    form = PostForm(
        initial={"visibility": request.session["active_user"].source.privacy}
    )
    try:
        prev = data[0]._pagination_prev
        if len(mastodon.timeline(min_id=prev["min_id"])) == 0:
            prev = None
        else:
            prev["min_id"] = data[0].id
    except (IndexError, AttributeError, KeyError):
        prev = None
    try:
        next = data[-1]._pagination_next
        next["max_id"] = data[-1].id
    except (IndexError, AttributeError, KeyError):
        next = None

    notifications = _notes_count(account, mastodon)
    filters = get_filters(mastodon, filter_context)

    # This filtering has to be done *after* getting next/prev links
    if account.preferences.filter_replies:
        data = [x for x in data if not x.in_reply_to_id]
    if account.preferences.filter_boosts:
        data = [x for x in data if not x.reblog]

    # Apply filters
    data = [x for x in data if not toot_matches_filters(x, filters)]

    return render(
        request,
        "main/%s_timeline.html" % timeline,
        {
            "toots": data,
            "form": form,
            "timeline": timeline,
            "timeline_name": timeline_name,
            "own_acct": request.session["active_user"],
            "preferences": account.preferences,
            "notifications": notifications,
            "prev": prev,
            "next": next,
        },
    )


def get_filters(mastodon, context=None):
    try:
        mastodon.version_check_mode = 'none'
        if context:
            return [ff for ff in mastodon.filters() if context in ff.context]
        else:
            return mastodon.filters()
    except:
        return []


def toot_matches_filters(toot, filters=[]):
    if not filters:
        return False

    def maybe_rewrite_filter(filter):
        if filter.whole_word:
            return f"\\b{filter.phrase}\\b"
        else:
            return filter.phrase

    phrases = [maybe_rewrite_filter(x) for x in filters]
    pattern = "|".join(phrases)
    try:
        if toot.get("type") in ["reblog", "favourite"]:
            return re.search(
                pattern, toot.status.spoiler_text + toot.status.content, re.I
            )
        return re.search(pattern, toot.spoiler_text + toot.content, re.I)
    except:
        return False


def switch_accounts(request, new_account):
    """Try to switch accounts to the specified account, if it is already in
    the user's session. Sets up new session variables. Returns boolean success
    code."""
    accounts_dict = request.session.get("accounts_dict")
    if not accounts_dict or not new_account in accounts_dict.keys():
        return False
    try:
        account = Account.objects.get(id=accounts_dict[new_account]["account_id"])
        if account.username != new_account:
            return False
    except Account.DoesNotExist:
        return False

    request.session["active_username"] = account.username
    request.session["active_instance"] = account.client.api_base_id
    account, mastodon = get_usercontext(request)
    request.session["active_user"] = mastodon.account_verify_credentials()
    accounts_dict[new_account]["user"] = request.session["active_user"]
    request.session["accounts_dict"] = accounts_dict
    return True


def forget_account(request, account_name):
    """Forget that you were logged into an account. If it's the last one, log out
    entirely. Sets up session variables. Returns a redirect to the correct
    view.
    """
    accounts_dict = request.session.get("accounts_dict")
    if not accounts_dict or not account_name in accounts_dict.keys():
        return redirect("accounts")
    del accounts_dict[account_name]

brutaldon/templates/setup/login-oauth.html
{% extends "base.html" %}
{% load widget_tweaks %}

{% block content %}
    <h1 class="title">Log in to your instance</h1>

    <form method="post" action="{% url "login" %}">
        {% csrf_token %}
        <div class="field">
            <label class="label">{{ form.instance.label  }}</label>
            <div class="control has-icons-left">
                {% render_field form.instance class+="input" %}
                <span class="icon is-small is-left">
                    <i class="fa fa-mastodon"></i>
                </span>
            </div>
        </div>

        <div class="field">
            <input type="submit" name="log_in"
                   value="Log in" class="button is-primary" >
        </div>
    </form>

    <div class="notification">
        <button class="delete"></button>
        <div>
            Not able to log in with this form? Maybe your brutaldon instance isn't
            visible on the internet to your Mastodon instance? If so, you can use
            the <a href="{% url "oldlogin" %}">old login form</a>.
        </div>
    </div>

{% endblock %}

brutaldon/templates/setup/login.html
{% extends "base.html" %}
{% load widget_tweaks %}

{% block content %}
    <h1 class="title">Log in to your instance</h1>

    <form method="post" action="{% url "oldlogin" %}">
        {% csrf_token %}
        <div class="field">
            <label class="label">{{ form.instance.label  }}</label>
            <div class="control has-icons-left">
                {% render_field form.instance class+="input" %}
                <span class="icon is-small is-left">
                    <i class="fa fa-mastodon"></i>
                </span>
            </div>
        </div>

        <div class="field">
            <label class="label">{{ form.email.label }}</label>
            <div class="control has-icons-left">
                {% render_field form.email class+="input" %}
                <span class="icon is-small is-left">
                    <i class="fa fa-user"></i>
                </span>
            </div>
        </div>
        <div class="field" >
            <label class="label" >{{ form.password.label }}</label>
            <div class="control has-icons-left" >
                {% render_field form.password class+="input" type="password" %}
                <span class="icon is-small is-left">
                    <i class="fa fa-lock" ></i>
                </span>
            </div>
        </div>
        <div class="field">
            <input type="submit" name="log_in"
                   value="Log in" class="button is-primary" >
        </div>
    </form>
    {% if form.errors %}
    <p class="error">
      {{ form.non_field_errors | escape }}
    </p>
    {% endif %}

    <div class="notification">
        <button class="delete"></button>
        <p>
            This information is only used to log you in to your instance for the
            first time. Brutaldon never stores your username and password; it
            only uses it to acquire a token which you can disable from the
            settings page of your Mastodon instance. However, you do need to
            absolutely trust the person running this copy of brutaldon! If that's
            not the case, use the <a href="{% url "login" %}">OAuth login form</a>.
        </p>
    </div>

{% endblock %}

brutaldon/templates/setup/settings.html
{% extends "base.html" %}
{% load widget_tweaks %}

{% block content %}
<div class="container">
    <h1 class="title">Settings</h1>
    <form method="post" action="{% url "settings" %}" >
        {% csrf_token %}

        <h2 class="subtitle">General Options</h2>
        <div class="field">
            <label class="label" for="id_theme">{{ form.theme.label }}</label>
            <div class="control has-icons-left">
                <div class="select">
                    {% render_field form.theme class+="select" %}
                    <span class="icon is-small is-left">
                        <span class="fa fa-paint-brush"></span>
                </div>
            </div>
        </div>

        <div class="field">
            <label class="label" for="id_timezone">{{ form.timezone.label }}</label>
            <div class="control has-icons-left">
                <div class="select">
                    {% render_field form.timezone class+="select" %}
                    <span class="icon is-small is-left">
                        <span class="fa fa-clock-o"></span>
                </div>
            </div>
        </div>

        <h2 class="subtitle">Content Options</h2>
        <div class="columns">
            <div class="column is-quarter">
                <label class="label checkbox" for="id_preview_sensitive">
                    {% render_field form.preview_sensitive class+="checkbox" %}
                    {{ form.preview_sensitive.label }}
                </label>
            </div>
            <div class="column is-quarter">
                <p class="notification is-info preferences-help">
                    {{ form.preview_sensitive.help_text }}
                </p>
            </div>
            <div class="column is-half">

            </div>
        </div>

        <h2 class="subtitle">Timeline Options</h2>
        <div class="field">
            <label class="label checkbox">
                {% render_field form.filter_replies %}
                {{ form.filter_replies.label  }}
            </label>
        </div>
        <div class="field">
            <label class="label checkbox"">
                {% render_field form.filter_boosts %}
                {{ form.filter_boosts.label  }}
            </label>
        </div>
        <div class="columns">
            <div class="column is-quarter">
                <label class="label checkbox" for="id_filter_notifications">
                    {% render_field form.filter_notifications class+="checkbox" %}
                    {{ form.filter_notifications.label }}
                </label>
            </div>
            <div class="column is-quarter">
                <p class="notification is-info preferences-help">
                    {{ form.filter_notifications.help_text }}
                </p>
            </div>
            <div class="column is-half">

            </div>
        </div>
        <div class="columns">
            <div class="column is-quarter">
                <label class="label checkbox" for="id_bundle_notifications">
                    {% render_field form.bundle_notifications class+="checkbox" %}
                    {{ form.bundle_notifications.label }}
                </label>
            </div>
            <div class="column is-quarter">
                <p class="notification is-info preferences-help">
                    {{ form.bundle_notifications.help_text }}
                </p>
            </div>
            <div class="column is-half">

            </div>
        </div>

        <h2 class="subtitle">JavaScript Options</h2>
        <div class="columns">
            <div class="column is-quarter">
                <label class="label checkbox" for="id_no_javascript">
                    {% render_field form.no_javascript class+="checkbox" %}
                    {{ form.no_javascript.label }}
                </label>
            </div>
            <div class="column is-quarter">
                <p class="notification is-info preferences-help">
                    {{ form.no_javascript.help_text }}
                </p>
            </div>
            <div class="column is-half">

            </div>
        </div>
        <div class="columns">
            <div class="column is-quarter">
                <label class="label checkbox" for="id_notifications">
                    {% render_field form.notifications class+="checkbox" %}
                    {{ form.notifications.label }}
                </label>
            </div>
            <div class="column is-quarter">
                <p class="notification is-info preferences-help">
                    {{ form.notifications.help_text }}
                </p>
            </div>
            <div class="column is-half">

            </div>
        </div>
        <div class="columns">
            <div class="column is-quarter">
                <label class="label checkbox" for="id_click_to_load">
                    {% render_field form.click_to_load class+="checkbox" %}
                    {{ form.click_to_load.label }}
                </label>
            </div>
            <div class="column is-quarter">
                <p class="notification is-info preferences-help">
                    {{ form.click_to_load.help_text }}
                </p>
            </div>
            <div class="column is-half">

            </div>
        </div>
        <div class="columns">
            <div class="column is-quarter">
                <label class="label checkbox" for="id_lightbox">
                    {% render_field form.lightbox class+="checkbox" %}
                    {{ form.lightbox.label }}
                </label>
            </div>
            <div class="column is-quarter">
                <p class="notification is-info preferences-help">
                    {{ form.lightbox.help_text }}
                </p>
            </div>
            <div class="column is-half">

            </div>
        </div>

        <div class="columns">
            <div class="column is-quarter">
                <label class="label" for="id_poll_frequency">
                    {{ form.poll_frequency.label }}
                </label>
                <div class="control">
                    {% render_field form.poll_frequency class+="input" %}
                </div>
            </div>
            <div class="column is-quarter">
                <p class="notification is-info preferences-help">
                    {{ form.poll_frequency.help_text }}
                </p>
            </div>
            <div class="column is-half">

            </div>
        </div>

        <div class="field">
            <input type="submit" name="submit"
                   value="Save" class="button is-primary" >
        </div>
    </form>

    <h2 class="subtitle">Bookmarklet</h2>
    <p>
        <a href="{{ bookmarklet_url }}">Share via brutaldon</a>
    </p>

    <h2 class="subtitle">Filters and More</h2>
    <p><a href="{% url "list_filters" %}">List filters</a></p>
    <p><a href="{% url "follow_requests" %}">Follow requests</a></p>

</div>
{% endblock %}